package com.us.g2g.hbm;
// Generated Aug 3, 2017 12:41:26 AM by Hibernate Tools 5.2.3.Final

import java.util.Date;

import com.google.gson.annotations.Expose;

/**
 * Comment generated by hbm2java
 */
public class Comment implements java.io.Serializable {

	@Expose
	private Integer id;
	private Event event;
	private User userByApprovedBy;
	@Expose
	private String commentedBy;

	private User userByPostedBy;
	@Expose
	private String text;
	@Expose
	private byte visible;
	@Expose
	private Date dateTime;
	@Expose
	private Date approvedOn;

	public Comment() {
		visible =  1;
		dateTime = new Date();
		
	}

	public Comment(byte visible, Date dateTime) {
		this.visible = visible;
		this.dateTime = dateTime;
	}

	public Comment(Event event, User userByApprovedBy, User userByPostedBy, String text, byte visible, Date dateTime,
			Date approvedOn) {
		this.event = event;
		this.userByApprovedBy = userByApprovedBy;
		this.userByPostedBy = userByPostedBy;
		this.text = text;
		this.visible = visible;
		this.dateTime = dateTime;
		this.approvedOn = approvedOn;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Event getEvent() {
		return this.event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	public User getUserByApprovedBy() {
		return this.userByApprovedBy;
	}

	public void setUserByApprovedBy(User userByApprovedBy) {
		this.userByApprovedBy = userByApprovedBy;
	}

	public User getUserByPostedBy() {
		return this.userByPostedBy;
	}

	public void setUserByPostedBy(User userByPostedBy) {
		this.userByPostedBy = userByPostedBy;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public byte getVisible() {
		return this.visible;
	}

	public void setVisible(byte visible) {
		this.visible = visible;
	}

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	public Date getApprovedOn() {
		return this.approvedOn;
	}

	public void setApprovedOn(Date approvedOn) {
		this.approvedOn = approvedOn;
	}

	public String getCommentedBy() {
		return commentedBy;
	}

	public void setCommentedBy(String commentedBy) {
		this.commentedBy = commentedBy;
	}

	
}
