package com.us.g2g.hbm;
// Generated Aug 3, 2017 12:41:26 AM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.google.gson.annotations.Expose;

/**
 * Event generated by hbm2java
 */
public class Event implements java.io.Serializable {

	@Expose
	private Integer id;
	@Expose
	private User userByCreatedBy;
	@Expose
	private User userByApprovedBy;
	@Expose
	private String title;
	@Expose
	private String description;
	@Expose
	private Double lat;
	@Expose
	private Double lng;
	@Expose
	private Integer estimatedBudget;
	@Expose
	private String receivedFund;
	@Expose
	private String exepectedFund;
	@Expose
	private String pocName;
	@Expose
	private String pocContact;
	@Expose
	private String occuranceDate;
	@Expose
	private String occuranceTime;
	@Expose
	private Date dateTime;
	@Expose
	private String status;
	@Expose
	private Date approvedOn;

	@Expose
	private Set<Payment> payments = new HashSet<Payment>(0);
	@Expose
	private Set<Participant> participants = new HashSet<Participant>(0);
	@Expose
	private Set<Photo> photos = new HashSet<Photo>(0);
	@Expose
	private Set<Comment> comments = new HashSet<Comment>(0);

	public Event() {
		dateTime = new Date();
	}

	public Event(User userByCreatedBy, User userByApprovedBy, String title, String description, Double lat, Double lng,
			Integer estimatedBudget, String receivedFund, String exepectedFund, String pocName, String pocContact,
			Date dateTime, String status, Date approvedOn, Set<Payment> payments, Set<Participant> participants,
			Set<Photo> photos, Set<Comment> comments) {
		this.userByCreatedBy = userByCreatedBy;
		this.userByApprovedBy = userByApprovedBy;
		this.title = title;
		this.description = description;
		this.lat = lat;
		this.lng = lng;
		this.estimatedBudget = estimatedBudget;
		this.receivedFund = receivedFund;
		this.exepectedFund = exepectedFund;
		this.pocName = pocName;
		this.pocContact = pocContact;
		this.dateTime = dateTime;
		this.status = status;
		this.approvedOn = approvedOn;
		this.payments = payments;
		this.participants = participants;
		this.photos = photos;
		this.comments = comments;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUserByCreatedBy() {
		return this.userByCreatedBy;
	}

	public void setUserByCreatedBy(User userByCreatedBy) {
		this.userByCreatedBy = userByCreatedBy;
	}

	public User getUserByApprovedBy() {
		return this.userByApprovedBy;
	}

	public void setUserByApprovedBy(User userByApprovedBy) {
		this.userByApprovedBy = userByApprovedBy;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Double getLat() {
		return this.lat;
	}

	public void setLat(Double lat) {
		this.lat = lat;
	}

	public Double getLng() {
		return this.lng;
	}

	public void setLng(Double lng) {
		this.lng = lng;
	}

	public Integer getEstimatedBudget() {
		return this.estimatedBudget;
	}

	public void setEstimatedBudget(Integer estimatedBudget) {
		this.estimatedBudget = estimatedBudget;
	}

	public String getReceivedFund() {
		return this.receivedFund;
	}

	public void setReceivedFund(String receivedFund) {
		this.receivedFund = receivedFund;
	}

	public String getExepectedFund() {
		return this.exepectedFund;
	}

	public void setExepectedFund(String exepectedFund) {
		this.exepectedFund = exepectedFund;
	}

	public String getPocName() {
		return this.pocName;
	}

	public void setPocName(String pocName) {
		this.pocName = pocName;
	}

	public String getPocContact() {
		return this.pocContact;
	}

	public void setPocContact(String pocContact) {
		this.pocContact = pocContact;
	}

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getApprovedOn() {
		return this.approvedOn;
	}

	public void setApprovedOn(Date approvedOn) {
		this.approvedOn = approvedOn;
	}

	public Set<Payment> getPayments() {
		return this.payments;
	}

	public void setPayments(Set<Payment> payments) {
		this.payments = payments;
	}

	public Set<Participant> getParticipants() {
		return this.participants;
	}

	public void setParticipants(Set<Participant> participants) {
		this.participants = participants;
	}

	public Set<Photo> getPhotos() {
		return this.photos;
	}

	public void setPhotos(Set<Photo> photos) {
		this.photos = photos;
	}

	public Set<Comment> getComments() {
		return this.comments;
	}

	public void setComments(Set<Comment> comments) {
		this.comments = comments;
	}

	public String getOccuranceDate() {
		return occuranceDate;
	}

	public void setOccuranceDate(String occuranceDate) {
		this.occuranceDate = occuranceDate;
	}

	public String getOccuranceTime() {
		return occuranceTime;
	}

	public void setOccuranceTime(String occuranceTime) {
		this.occuranceTime = occuranceTime;
	}

}
