package com.us.g2g.hbm;
// Generated Aug 3, 2017 12:41:26 AM by Hibernate Tools 5.2.3.Final

import java.util.Date;

import com.google.gson.annotations.Expose;

/**
 * Participant generated by hbm2java
 */
public class Participant implements java.io.Serializable {

	private Integer id;
	private Event event;
	private User user;
	@Expose
	private String name;
	@Expose
	private Date dateTime;
	@Expose
	private String note;
	@Expose
	private String status;

	public Participant() {
		dateTime = new Date();
	}

	public Participant(Date dateTime) {
		this.dateTime = dateTime;
	}

	public Participant(Event event, User user, Date dateTime, String note, String status) {
		this.event = event;
		this.user = user;
		this.dateTime = dateTime;
		this.note = note;
		this.status = status;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Event getEvent() {
		return this.event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	

}
