package com.us.g2g.hbm;
// Generated Aug 3, 2017 12:41:26 AM by Hibernate Tools 5.2.3.Final

import java.util.Date;

import com.google.gson.annotations.Expose;

/**
 * Payment generated by hbm2java
 */
public class Payment implements java.io.Serializable {

	@Expose
	private Integer id;
	private Event event;
	private User user;
	@Expose
	private String paidBy;
	@Expose
	private String transactionId;
	@Expose
	private String gatewayId;
	@Expose
	private Integer amount;
	@Expose
	private Date paidOn;
	@Expose
	private String status;
	@Expose
	private String note;

	public Payment() {
		paidOn = new Date();
	}

	public Payment(Date paidOn) {
		this.paidOn = paidOn;
	}

	public Payment(Event event, User user, String transactionId, String gatewayId, Integer amount, Date paidOn,
			String status, String note) {
		this.event = event;
		this.user = user;
		this.transactionId = transactionId;
		this.gatewayId = gatewayId;
		this.amount = amount;
		this.paidOn = paidOn;
		this.status = status;
		this.note = note;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Event getEvent() {
		return this.event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	public String getGatewayId() {
		return this.gatewayId;
	}

	public void setGatewayId(String gatewayId) {
		this.gatewayId = gatewayId;
	}

	public Integer getAmount() {
		return this.amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	public Date getPaidOn() {
		return this.paidOn;
	}

	public void setPaidOn(Date paidOn) {
		this.paidOn = paidOn;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public String getPaidBy() {
		return paidBy;
	}

	public void setPaidBy(String paidBy) {
		this.paidBy = paidBy;
	}
	

}
