package com.us.g2g.hbm;
// Generated Aug 3, 2017 12:41:26 AM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

import com.google.gson.annotations.Expose;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	@Expose
	private Integer id;
	@Expose
	private String name;
	@Expose
	private String shortName;
	@Expose
	private String email;
	@Expose
	private String password;
	@Expose
	private String role;
	private Set<Comment> commentsForApprovedBy = new HashSet<Comment>(0);
	private Set<Photo> photosForUserId = new HashSet<Photo>(0);
	private Set<Comment> commentsForPostedBy = new HashSet<Comment>(0);
	private Set<Participant> participants = new HashSet<Participant>(0);
	private Set<Event> eventsForCreatedBy = new HashSet<Event>(0);
	private Set<Payment> payments = new HashSet<Payment>(0);
	private Set<Photo> photosForApprovedBy = new HashSet<Photo>(0);
	private Set<Event> eventsForApprovedBy = new HashSet<Event>(0);

	public User() {
	}

	public User(String name, String shortName, String email, String password, String role,
			Set<Comment> commentsForApprovedBy, Set<Photo> photosForUserId, Set<Comment> commentsForPostedBy,
			Set<Participant> participants, Set<Event> eventsForCreatedBy, Set<Payment> payments,
			Set<Photo> photosForApprovedBy, Set<Event> eventsForApprovedBy) {
		this.name = name;
		this.shortName = shortName;
		this.email = email;
		this.password = password;
		this.role = role;
		this.commentsForApprovedBy = commentsForApprovedBy;
		this.photosForUserId = photosForUserId;
		this.commentsForPostedBy = commentsForPostedBy;
		this.participants = participants;
		this.eventsForCreatedBy = eventsForCreatedBy;
		this.payments = payments;
		this.photosForApprovedBy = photosForApprovedBy;
		this.eventsForApprovedBy = eventsForApprovedBy;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getShortName() {
		return this.shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public Set<Comment> getCommentsForApprovedBy() {
		return this.commentsForApprovedBy;
	}

	public void setCommentsForApprovedBy(Set<Comment> commentsForApprovedBy) {
		this.commentsForApprovedBy = commentsForApprovedBy;
	}

	public Set<Photo> getPhotosForUserId() {
		return this.photosForUserId;
	}

	public void setPhotosForUserId(Set<Photo> photosForUserId) {
		this.photosForUserId = photosForUserId;
	}

	public Set<Comment> getCommentsForPostedBy() {
		return this.commentsForPostedBy;
	}

	public void setCommentsForPostedBy(Set<Comment> commentsForPostedBy) {
		this.commentsForPostedBy = commentsForPostedBy;
	}

	public Set<Participant> getParticipants() {
		return this.participants;
	}

	public void setParticipants(Set<Participant> participants) {
		this.participants = participants;
	}

	public Set<Event> getEventsForCreatedBy() {
		return this.eventsForCreatedBy;
	}

	public void setEventsForCreatedBy(Set<Event> eventsForCreatedBy) {
		this.eventsForCreatedBy = eventsForCreatedBy;
	}

	public Set<Payment> getPayments() {
		return this.payments;
	}

	public void setPayments(Set<Payment> payments) {
		this.payments = payments;
	}

	public Set<Photo> getPhotosForApprovedBy() {
		return this.photosForApprovedBy;
	}

	public void setPhotosForApprovedBy(Set<Photo> photosForApprovedBy) {
		this.photosForApprovedBy = photosForApprovedBy;
	}

	public Set<Event> getEventsForApprovedBy() {
		return this.eventsForApprovedBy;
	}

	public void setEventsForApprovedBy(Set<Event> eventsForApprovedBy) {
		this.eventsForApprovedBy = eventsForApprovedBy;
	}

}
